### ISSUE TITLE
Question about the netPlot_HFHS function mentioned in the vignette

### ISSUE THREAD

**Issue by Charlie-Hong-smu** [SarithaKodikara/LUPINE#1]
Hi there, I came across the netPlot_HFHS function in the vignette of the LUPINE package and I'm interested in using it for network analysis. However, I can't seem to find this function within the package. Could you please provide some guidance on where I can find the netPlot_HFHS function or clarify if it's part of the package?

Thanks.

p1 <- netPlot_HFHS(net_Normal[[3]], col_vec, "Normal Day7")
p2 <- netPlot_HFHS(net_HFHS[[3]], col_vec, "HFHS Day7")

**Comment by SarithaKodikara** [comment]
Hi Charlie,

Thank you for your interest in LUPINE! The `netPlot_HFHS` function is not included in the LUPINE package, as it was designed specifically for the High Fat High Sugar (HFHS) case study. I am working on a more generalisable network visualisation that will be included in the package in the future. In the meantime, you can access the relevant code [here](https://github.com/SarithaKodikara/LUPINE/blob/978b0aca5e441ec934bf1c7cca22915199c10346/vignettes/example.Rmd#L45).

Regards
Saritha

**Comment by Charlie-Hong-smu** [comment]
Hi,

Thanks for clarifying the netPlot_HFHS function. I appreciate your help.

I noticed the output list from LUPINE function. It seems to include adjacency matrices for three time points, but I was expecting matrices for four time points, including Day 0. The structure shows matrices for lists [[1]], [[2]], and [[3]], which I assume correspond to Days 1, 4, and 7, respectively. Is there a reason why Day 0's adjacency matrix is not included? Or is there something wrong with my understanding?

Thanks again for your assistance.
![屏幕截图 2024-10-18 104822](https://github.com/user-attachments/assets/f96951a2-8189-44fe-abfb-e6012e98b9e9)

**Comment by SarithaKodikara** [comment]
Hi Charlie

The initial time point (day 0) network is absent from the longitudinal scheme as we require at least one prior time point for inference. If you need to get the inference for day 0 then the single time point version of LUPINE is the only way to get it (i.e. LUPINE(..., single = TRUE). 

Regards
Saritha

**Comment by Charlie-Hong-smu** [comment]
Hi, Saritha

You really help me a lot! Thanks for solving my problems!

**Comment by SarithaKodikara** [comment]
My pleasure Charlie. Please reach out to me if you have any more questions.
